[project]
name = "clickhouse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt>=1.0.0.40.11",
    "dbt-clickhouse>=1.9.6",
    "dbt-core>=1.10.15",
]
